name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/html/
            rm -rf /home/cloned-repo/
            cd /var/www
            mkdir html
            cd /home
            mkdir cloned-repo
            cd cloned-repo
            git clone https://github.com/Andrii-Yukhymenko/auto-deploy-to-digitalocean.git
            cd auto-deploy-to-digitalocean/
#           ^--- The name of your repository
            cp -r app/* /var/www/html
#           ^--- The name of the folder with the finished build
